### ISSUE TITLE
use a PEAR derived coding style

### ISSUE THREAD

**Issue by lsmith77** [winmillwill/BadFaith#1]
sorry .. i should have pointed this out earlier ..
i would recommend if you would use for example the Symfony coding style:
http://symfony.com/doc/current/contributing/code/standards.html

not sure on the particulars of the Drupal OO CS

**Comment by winmillwill** [comment]
No one is sure of the particulars of Drupal OO CS because the most monstrously OO module (Views) uses a style that contradicts the style given on the drupal.org coding style pages. :)

I've begun addressing it. Your eyes should not bleed next time you look at the code.

**Comment by winmillwill** [comment]
to wit: this is what I'm using now https://gist.github.com/2292885
