### ISSUE TITLE
Make the library PSR-0 compliant

### ISSUE THREAD

**Issue by stof** [winmillwill/BadFaith#2]
The files should be moved to `lib/BadFaith` so that they follow the PSR-0 standard. Btw, this will fix your composer.json as it already advocates following psr-0

On a side note, the composer.json misses a bunch of section for shared packages (keywords, description, authors, ...). You could use the `composer.phar validate` command to see it.

**Comment by winmillwill** [comment]
Done, thanks for the heads up!
