### ISSUE TITLE
update the README with an example for negotiation

### ISSUE THREAD

**Issue by lsmith77** [winmillwill/BadFaith#5]
could you add an example into the README illustrating how you envision the API for going an actual negotiation?

**Comment by winmillwill** [comment]
I just updated the README, but it's still hand-wavy as I have yet to actually implement the sorting of header fields for UA-only negotiation or the actual algo for Apache as discussed.

**Comment by lsmith77** [comment]
would be good to also implement a way to set the accept headers from a Symfony2 Request object as an option. Negotiator::initLists() seems a bit unnecessary ... why not do this in the methods for setting the headers to begin with?

**Comment by lsmith77** [comment]
setting of the available variants seems a bit strange .. why not provide an explicit method here too?
